name: Create a Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  check-workflows:
    uses: ./.github/workflows/check-workflows.yml

  build-artifacts:
    needs: check-workflows
    uses: ./.github/workflows/windows-build.yml
    with: 
      upload-artifacts: true

  create-release:
    needs: build-artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Create a Release
      run: gh release create ${{ github.ref }} -F ReleaseNote.md

    - name: Download cobj.exe
      uses: actions/download-artifact@v4
      with:
        name: cobj.exe

    - name: Download libcobj.jar
      uses: actions/download-artifact@v4
      with:
        name: libcobj.jar

    - name: Publish artifacts
      run: | 
        gh release upload ${{ github.ref_name }} cobj.exe --clobber
        gh release upload ${{ github.ref_name }} libcobj.jar --clobber
        gh release upload ${{ github.ref_name }} config/default.conf --clobber

  # publish libcobj.jar to GitHub Packages
  publish:
    needs: check-workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd ../
          mv opensourcecobol4j/* .
          mv libcobj/* opensourcecobol4j
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Publish package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
