name: test on push

on:
  push:
    paths-ignore:
      - '*.md'
      - 'ChangeLog'
      - 'NEWS'
      - 'README'
      - 'COPYING'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-workflows:
    uses: ./.github/workflows/check-workflows.yml

  build:
    needs: check-workflows
    strategy:
      matrix:
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}

  build-utf8:
    needs: check-workflows
    strategy:
      matrix:
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      configure-args: --enable-utf8

  run-test-other:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        test_name:
          - "command-line-options"
          - "data-rep"
          - "i18n_sjis"
          - "jp-compat"
          - "run"
          - "syntax"
          - "cobj-idx"
          - "misc"
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-other.yml
    with:
      test-name: ${{ matrix.test_name }}
      os: ${{ matrix.os }}
  
  run-test-other-utf8:
    needs: build-utf8
    strategy:
      fail-fast: false
      matrix:
        test_name:
          - "command-line-options"
          - "data-rep"
          - "cobol_utf8"
          #- "i18n_utf8"
          - "jp-compat"
          - "run"
          - "syntax"
          - "cobj-idx"
          #- "misc"
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-other.yml
    with:
      test-name: ${{ matrix.test_name }}
      os: ${{ matrix.os }}
      configure-args: --enable-utf8

  run-test-cobj-api:
    needs: build
    strategy:
      matrix:
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-cobj-api.yml
    with:
      os: ${{ matrix.os }}

  run-test-nist:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        test_name: ["IC", "IF", "IX", "NC", "OB", "RL", "SG", "SM", "SQ", "ST"]
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: true
      os: ${{ matrix.os }}

  run-test-nist-utf8:
    needs: build-utf8
    strategy:
      fail-fast: false
      matrix:
        test_name: ["IC", "IF", "IX", "NC", "OB", "RL", "SG", "SM", "SQ", "ST"]
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: true
      os: ${{ matrix.os }}
      configure-args: --enable-utf8

  run-test-nist-extra:
    needs: build
    strategy:
      matrix:
        test_name: ["CM", "DB", "RW"]
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: false
      os: ${{ matrix.os }}

  build-gcc9:
    needs: check-workflows
    uses: ./.github/workflows/build-gcc9.yml

  javadoc:
    needs: check-workflows
    uses: ./.github/workflows/javadoc.yml

  check-missing-javadoc:
    needs: check-workflows
    uses: ./.github/workflows/check-missing-javadoc.yml

  windows-build:
    needs: check-workflows
    uses: ./.github/workflows/windows-build.yml
    with: 
      upload-artifacts: true

  windows-test:
    needs: windows-build
    strategy:
       matrix:
         test_name: ["IC", "IF", "IX", "NC", "OB", "RL", "SG", "SM", "SQ", "ST"]
    uses: ./.github/workflows/windows-test.yml
    with:
      test-name: ${{ matrix.test_name }}

  static-analysis:
    needs: check-workflows
    uses: ./.github/workflows/static-analysis.yml
