name: static analysis

on:
  workflow_call:

permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-22.04
    container:
      image: almalinux:9
    steps:
      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install static analysis tools
        run: |
          dnf update -y
          dnf install -y epel-release
          dnf install -y gcc make bison flex automake autoconf diffutils gettext java-21-openjdk-devel git-clang-format cppcheck

      - name: Install opensource COBOL 4J
        run: |
          ./configure --prefix=/usr/
          make
          make install

      - name: Check format with google-java-format and clang-format
        run: |
          ./check-format

      - name: Run SpotBugs
        working-directory: libcobj
        run: |
          ./gradlew spotbugsMain

      - name: Run PMD
        working-directory: libcobj
        run: |
          ./gradlew pmdMain

      - name: Run cppcheck
        working-directory: cobj
        run: |
          ./cpp-check